/** @type {import('tailwindcss').Config} */
// Migrado del CDN (window.__tailwindConfig en index.html) el 2026-08-03.
// Copia EXACTA — fidelidad CSS absoluta con Stitch, cero valores alterados.
const path = require('path');
module.exports = {
  darkMode: 'class',
  // FIX (2026-08-08): rutas relativas dependían del cwd del proceso que
  // invoca a Tailwind (PM2 arranca con cwd = raíz del repo, no client/) —
  // sin coincidencias, Tailwind generaba solo preflight, cero utilidades.
  content: [
    path.join(__dirname, 'index.html'),
    path.join(__dirname, 'src/**/*.{js,ts,jsx,tsx}'),
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Hanken Grotesk', 'sans-serif'],
        headline: ['Hanken Grotesk'],
        label: ['JetBrains Mono'],
        body: ['Hanken Grotesk'],
        display: ['Hanken Grotesk'],
        'headline-xl': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'body-md': ['Hanken Grotesk'],
        'body-sm': ['Hanken Grotesk'],
        'label-md': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
      },
      spacing: {
        xs: '4px', sm: '8px', md: '16px', lg: '24px', xl: '32px',
        gutter: '20px', unit: '4px', 'container-max': '1440px',
      },
      colors: {
        primary: '#000000',
        secondary: '#0058be',
        surface: '#ffffff',
        background: '#f7f9fb',
        onSurface: { DEFAULT: '#191c1e', variant: '#45464d' },
        outline: { DEFAULT: '#76777d', variant: '#c6c6cd' },
        'on-background': '#191c1e',
        'on-surface': '#191c1e',
        'on-surface-variant': '#45464d',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-low': '#f2f4f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-tint': '#565e74',
        'surface-variant': '#e0e3e5',
        'secondary-container': '#2170e4',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        'primary-container': '#131b2e',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-container': '#7c839b',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'inverse-primary': '#bec6e0',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'outline-variant': '#c6c6cd',
        tertiary: '#000000',
        'tertiary-container': '#0b1c30',
        'tertiary-fixed': '#d3e4fe',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#75859d',
        'on-tertiary-fixed': '#0b1c30',
        'on-tertiary-fixed-variant': '#38485d',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
