ENTIDADES_RADAR = [
    {
        "id": "ent-giz",
        "nombre": "GIZ - Agencia Alemana de Cooperacion Internacional",
        "sigla": "GIZ",
        "tipo": "bilateral",
        "pais": "Alemania",
        "bandera": "DE",
        "sectores": ["Paz", "Medio Ambiente", "Recursos Naturales", "Desarrollo Sostenible"],
        "sitio_web": "https://www.giz.de",
        "url_convocatorias": "https://www.giz.de/en/worldwide/latin-america.html",
        "contacto": "Oficina Regional America Latina",
        "email_contacto": "americalatina@giz.de",
        "convocatorias_activas": 3,
        "monto_total": 5000000,
        "moneda": "USD",
        "frecuencia": "trimestral",
        "ultima_convocatoria": "2026-05-01",
        "notas": "Cooperacion triangular. Enfoque en paz, medio ambiente.",
    },
    {
        "id": "ent-unesco",
        "nombre": "UNESCO",
        "sigla": "UNESCO",
        "tipo": "multilateral",
        "pais": "Naciones Unidas",
        "bandera": "UN",
        "sectores": ["Educacion", "Cultura", "Ciencia", "Patrimonio"],
        "sitio_web": "https://www.unesco.org",
        "url_convocatorias": "https://www.unesco.org/en/member-states-portal/participation-programme",
        "contacto": "Programa de Participacion",
        "email_contacto": "participation@unesco.org",
        "convocatorias_activas": 2,
        "monto_total": 50000,
        "moneda": "USD",
        "frecuencia": "anual",
        "ultima_convocatoria": "2026-01-15",
        "notas": "Programa de Participacion 2026-2027. Hasta USD 38,000.",
    },
    {
        "id": "ent-jica",
        "nombre": "JICA - Japan International Cooperation Agency",
        "sigla": "JICA",
        "tipo": "bilateral",
        "pais": "Japon",
        "bandera": "JP",
        "sectores": ["Desarrollo Comunitario", "Cooperativismo", "Infraestructura Social"],
        "sitio_web": "https://www.jica.go.jp",
        "url_convocatorias": "https://www.jica.go.jp/english/activities/index.html",
        "contacto": "Oficina Colombia",
        "email_contacto": "colombia@jica.go.jp",
        "convocatorias_activas": 2,
        "monto_total": 80000,
        "moneda": "USD",
        "frecuencia": "semestral",
        "ultima_convocatoria": "2026-03-01",
        "notas": "Proyectos comunitarios de seguridad humana. Hasta USD 80,000.",
    },
    {
        "id": "ent-ikea",
        "nombre": "IKEA Foundation",
        "sigla": "IKEA Foundation",
        "tipo": "privado",
        "pais": "Global",
        "bandera": "SE",
        "sectores": ["Impacto Social", "Desarrollo Comunitario", "Sostenibilidad"],
        "sitio_web": "https://ikeafoundation.org",
        "url_convocatorias": "https://ikeafoundation.org/our-focus/",
        "contacto": "Grant Relations",
        "email_contacto": "info@ikeafoundation.org",
        "convocatorias_activas": 2,
        "monto_total": 50000000,
        "moneda": "USD",
        "frecuencia": "variable",
        "ultima_convocatoria": "2026-02-01",
        "notas": "Proyectos de alto impacto y escala.",
    },
    {
        "id": "ent-unwomen",
        "nombre": "UN Women - ONU Mujeres",
        "sigla": "UN Women",
        "tipo": "multilateral",
        "pais": "Naciones Unidas",
        "bandera": "UN",
        "sectores": ["Igualdad de Genero", "Emprendimiento", "Paz", "Desarrollo Social"],
        "sitio_web": "https://www.unwomen.org",
        "url_convocatorias": "https://www.unwomen.org/en/trust-funds/fund-for-gender-equality",
        "contacto": "Fund for Gender Equality",
        "email_contacto": "fge@unwomen.org",
        "convocatorias_activas": 2,
        "monto_total": 500000,
        "moneda": "USD",
        "frecuencia": "anual",
        "ultima_convocatoria": "2026-04-15",
        "notas": "Subvenciones para organizaciones lideradas por mujeres.",
    },
    {
        "id": "ent-eu",
        "nombre": "Union Europea - European Commission",
        "sigla": "UE",
        "tipo": "multilateral",
        "pais": "Europa",
        "bandera": "EU",
        "sectores": ["Gobernanza", "Cambio Climatico", "Investigacion", "Educacion", "Ayuda Humanitaria"],
        "sitio_web": "https://ec.europa.eu",
        "url_convocatorias": "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities",
        "contacto": "Europe Direct",
        "email_contacto": "info@europea.eu",
        "convocatorias_activas": 15,
        "monto_total": 50000000,
        "moneda": "EUR",
        "frecuencia": "mensual",
        "ultima_convocatoria": "2026-05-01",
        "notas": "Portal de financiacion y licitaciones.",
    },
    {
        "id": "ent-sena",
        "nombre": "SENA - Fondo Emprender",
        "sigla": "SENA",
        "tipo": "gobierno",
        "pais": "Colombia",
        "bandera": "CO",
        "sectores": ["Emprendimiento", "Empresarial", "Formacion", "Empleo"],
        "sitio_web": "https://www.sena.edu.co",
        "url_convocatorias": "https://www.fondoemprender.com:48080/",
        "contacto": "Fondo Emprender",
        "email_contacto": "fondoemprender@sena.edu.co",
        "convocatorias_activas": 11,
        "monto_total": 282400000000,
        "moneda": "COP",
        "frecuencia": "mensual",
        "ultima_convocatoria": "2026-05-10",
        "notas": "Capital semilla condonable. 11 lineas.",
    },
    {
        "id": "ent-bid",
        "nombre": "BID - Banco Interamericano de Desarrollo",
        "sigla": "BID",
        "tipo": "multilateral",
        "pais": "Multilateral",
        "bandera": "BID",
        "sectores": ["Desarrollo Social", "Infraestructura", "Emprendimiento"],
        "sitio_web": "https://www.iadb.org",
        "url_convocatorias": "https://www.iadb.org/en/opportunities",
        "contacto": "Opportunities",
        "email_contacto": "opportunities@iadb.org",
        "convocatorias_activas": 8,
        "monto_total": 20000000,
        "moneda": "USD",
        "frecuencia": "trimestral",
        "ultima_convocatoria": "2026-02-15",
        "notas": "Donaciones para emprendimiento social.",
    },
    {
        "id": "ent-caf",
        "nombre": "CAF - Banco de Desarrollo de America Latina",
        "sigla": "CAF",
        "tipo": "multilateral",
        "pais": "Multilateral",
        "bandera": "CAF",
        "sectores": ["Accion Social", "Investigacion", "Desarrollo Sostenible"],
        "sitio_web": "https://www.caf.com",
        "url_convocatorias": "https://www.caf.com/es/convocatorias",
        "contacto": "Convocatorias",
        "email_contacto": "info@caf.com",
        "convocatorias_activas": 4,
        "monto_total": 10000000,
        "moneda": "USD",
        "frecuencia": "semestral",
        "ultima_convocatoria": "2026-03-01",
        "notas": "Cooperacion tecnica no reembolsable.",
    },
    {
        "id": "ent-bm",
        "nombre": "Banco Mundial",
        "sigla": "Banco Mundial",
        "tipo": "multilateral",
        "pais": "Multilateral",
        "bandera": "BM",
        "sectores": ["Medio Ambiente", "Cambio Climatico", "Desarrollo Sostenible"],
        "sitio_web": "https://www.bancomundial.org",
        "url_convocatorias": "https://www.bancomundial.org/en/what-we-do",
        "contacto": "GEF Secretariat",
        "email_contacto": "gefexecsec@worldbank.org",
        "convocatorias_activas": 3,
        "monto_total": 5000000,
        "moneda": "USD",
        "frecuencia": "semestral",
        "ultima_convocatoria": "2026-01-15",
        "notas": "Programa de Donaciones Pequenas (PDP).",
    },
    {
        "id": "ent-aecid",
        "nombre": "AECID - Agencia Espanola de Cooperacion Internacional",
        "sigla": "AECID",
        "tipo": "bilateral",
        "pais": "Espania",
        "bandera": "ES",
        "sectores": ["Genero", "Agua y Saneamiento", "Fortalecimiento Institucional"],
        "sitio_web": "https://www.aecid.org.co",
        "url_convocatorias": "https://apccolombia.gov.co/modalidades-de-cooperacion/cooperacion-triangular/convocatorias-cooperacion-triangular/programa-de",
        "contacto": "Oficina Colombia",
        "email_contacto": "colombia@aecid.es",
        "convocatorias_activas": 2,
        "monto_total": 3000000,
        "moneda": "EUR",
        "frecuencia": "anual",
        "ultima_convocatoria": "2026-02-01",
        "notas": "Plan Director 2024-2027. Cooperacion triangular.",
    },
    {
        "id": "ent-afd",
        "nombre": "AFD - Agence Francaise de Developpement",
        "sigla": "AFD",
        "tipo": "bilateral",
        "pais": "Francia",
        "bandera": "FR",
        "sectores": ["Cambio Climatico", "Biodiversidad", "Desarrollo Urbano"],
        "sitio_web": "https://www.afd.fr",
        "url_convocatorias": "https://www.afd.fr/en/projects/list",
        "contacto": "Projets",
        "email_contacto": "projets@afd.fr",
        "convocatorias_activas": 3,
        "monto_total": 20000000,
        "moneda": "EUR",
        "frecuencia": "trimestral",
        "ultima_convocatoria": "2026-03-15",
        "notas": "Transicion verde, biodiversidad y desarrollo urbano.",
    },
    {
        "id": "ent-pnud",
        "nombre": "PNUD - Programa de las Naciones Unidas para el Desarrollo",
        "sigla": "PNUD",
        "tipo": "multilateral",
        "pais": "Naciones Unidas",
        "bandera": "UN",
        "sectores": ["Desarrollo Sostenible", "Gobernabilidad", "Desarrollo Economico"],
        "sitio_web": "https://www.undp.org",
        "url_convocatorias": "https://www.undp.org/es/colombia/convocatorias-laborales",
        "contacto": "Colombia",
        "email_contacto": "colombia@undp.org",
        "convocatorias_activas": 4,
        "monto_total": 5000000,
        "moneda": "USD",
        "frecuencia": "trimestral",
        "ultima_convocatoria": "2026-02-20",
        "notas": "Asistencia tecnica para reduccion de pobreza y ODS.",
    },
    {
        "id": "ent-fontagro",
        "nombre": "FONTAGRO - Fondo Regional de Tecnologia Agropecuaria",
        "sigla": "FONTAGRO",
        "tipo": "multilateral",
        "pais": "Regional",
        "bandera": "FONTAGRO",
        "sectores": ["Agricola", "Agroindustria", "Investigacion", "Innovacion"],
        "sitio_web": "https://www.fontagro.org",
        "url_convocatorias": "https://fontagro.org/en/iniciativas/convocatorias/convocatoria-2026",
        "contacto": "Secretaria Tecnica",
        "email_contacto": "info@fontagro.org",
        "convocatorias_activas": 2,
        "monto_total": 2000000,
        "moneda": "USD",
        "frecuencia": "anual",
        "ultima_convocatoria": "2026-03-01",
        "notas": "Cofinanciamiento no reembolsable para innovacion agropecuaria.",
    },
    {
        "id": "ent-google",
        "nombre": "Google.org",
        "sigla": "Google",
        "tipo": "privado",
        "pais": "Global",
        "bandera": "US",
        "sectores": ["Comunicacion", "Tecnologia", "Desarrollo Social"],
        "sitio_web": "https://www.google.com",
        "url_convocatorias": "https://www.google.com/grants",
        "contacto": "Google Ad Grants",
        "email_contacto": "adgrants@google.com",
        "convocatorias_activas": 1,
        "monto_total": 10000,
        "moneda": "USD",
        "frecuencia": "continua",
        "ultima_convocatoria": "2026-01-01",
        "notas": "USD 10,000 mensuales en publicidad para ONGs.",
    },
    {
        "id": "ent-scotiabank",
        "nombre": "Scotiabank - ScotiaRISE",
        "sigla": "Scotiabank",
        "tipo": "privado",
        "pais": "Canada",
        "bandera": "CA",
        "sectores": ["Empleo", "Emprendimiento", "Inclusion Financiera"],
        "sitio_web": "https://www.scotiabank.com",
        "url_convocatorias": "https://www.scotiabank.com/ca/en/about/responsibility-impact/scotiarise/funding-guidelines-application.html",
        "contacto": "ScotiaRISE",
        "email_contacto": "scotiarise@scotiabank.com",
        "convocatorias_activas": 2,
        "monto_total": 500000,
        "moneda": "USD",
        "frecuencia": "anual",
        "ultima_convocatoria": "2026-04-01",
        "notas": "Inclusion financiera y empleo para jovenes.",
    },
    {
        "id": "ent-innpulsa",
        "nombre": "iNNpulsa Colombia",
        "sigla": "iNNpulsa",
        "tipo": "gobierno",
        "pais": "Colombia",
        "bandera": "CO",
        "sectores": ["Emprendimiento", "Innovacion", "Empresarial", "Tecnologia e Innovacion"],
        "sitio_web": "https://www.innpulsacolombia.com",
        "url_convocatorias": "https://www.innpulsacolombia.com/convocatorias.html",
        "contacto": "Convocatorias",
        "email_contacto": "info@innpulsacolombia.com",
        "convocatorias_activas": 5,
        "monto_total": 10000000000,
        "moneda": "COP",
        "frecuencia": "mensual",
        "ultima_convocatoria": "2026-05-01",
        "notas": "Emprendimiento de alto impacto.",
    },
    {
        "id": "ent-iom",
        "nombre": "OIM - Organizacion Internacional para las Migraciones",
        "sigla": "OIM",
        "tipo": "multilateral",
        "pais": "Naciones Unidas",
        "bandera": "UN",
        "sectores": ["Ayuda Humanitaria", "Desarrollo Social", "Poblacion Vulnerable"],
        "sitio_web": "https://www.iom.int",
        "url_convocatorias": "https://www.iom.int/funding-and-donors",
        "contacto": "Funding Unit",
        "email_contacto": "hq@iom.int",
        "convocatorias_activas": 4,
        "monto_total": 10000000,
        "moneda": "USD",
        "frecuencia": "variable",
        "ultima_convocatoria": "2026-02-15",
        "notas": "IOM Development Fund. Atencion a poblacion migrante.",
    },
    {
        "id": "ent-avina",
        "nombre": "Fundacion Avina",
        "sigla": "Avina Foundation",
        "tipo": "privado",
        "pais": "Panama",
        "bandera": "PA",
        "sectores": ["Cambio Social", "Sostenibilidad", "Desarrollo Comunitario"],
        "sitio_web": "https://www.avina.net",
        "url_convocatorias": "https://www.avina.net/en/what-we-do",
        "contacto": "Programa CollaborAction",
        "email_contacto": "info@avina.net",
        "convocatorias_activas": 3,
        "monto_total": 1000000,
        "moneda": "USD",
        "frecuencia": "variable",
        "ultima_convocatoria": "2026-03-01",
        "notas": "30 anos de experiencia. Enfoque en alianzas colaborativas.",
    },
    {
        "id": "ent-cosude",
        "nombre": "COSUDE - Agencia suiza para el Desarrollo",
        "sigla": "COSUDE",
        "tipo": "bilateral",
        "pais": "Suiza",
        "bandera": "CH",
        "sectores": ["Agua y Saneamiento", "Ayuda Humanitaria", "Competitividad Economica"],
        "sitio_web": "https://www.eda.admin.ch",
        "url_convocatorias": "https://www.eda.admin.ch/deza/en/home",
        "contacto": "Cooperacion Tecnica Colombia",
        "email_contacto": "bogota@eda.admin.ch",
        "convocatorias_activas": 2,
        "monto_total": 2000000,
        "moneda": "CHF",
        "frecuencia": "anual",
        "ultima_convocatoria": "2026-02-01",
        "notas": "Especializacion en ayuda humanitaria de emergencia y agua.",
    },
]